apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster-azure-aks
  labels:
    crossplane.io/xrd: compositeclusters.demo.anthos.com
    provider: azure
    cluster: aks
spec:
  compositeTypeRef:
    apiVersion: demo.anthos.com/v1
    kind:  CompositeCluster
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: resourcegroup
    base:
      apiVersion: azure.gke.cloud.google.com/v1beta1
      kind: ResourceGroup
      metadata:
        name: aks-crossplane
      spec:
        providerConfigRef:
          name: default-azure
        forProvider:
          location: East Us
  - name: akscluster
    base:
      apiVersion: containerservice.azure.gke.cloud.google.com/v1beta1
      kind: KubernetesCluster
      metadata:
        labels:
          role: controlplane
        # name: akscluster
      spec:
        providerConfigRef:
          name: default-azure
        forProvider:
          defaultNodePool:
          - name: default
            nodeCount: 1
            vmSize: Standard_D2_v2
          dnsPrefix: akscluster
          identity:
          - type: SystemAssigned
          location: East Us
          resourceGroupNameSelector:
            matchControllerRef: true
          oidcIssuerEnabled: true
          workloadIdentityEnabled: true
        writeConnectionSecretToRef:
#          name: kubeconfig
          namespace: default
    patches:
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.oidcIssuerUrl
      toFieldPath: status.odicIssuerUrl
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.k8sVersion
      toFieldPath: spec.forProvider.kubernetesVersion
    - fromFieldPath: spec.parameters.minNodeCount
      toFieldPath: spec.forProvider.defaultNodePool[0].nodeCount
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.forProvider.defaultNodePool[0].vmSize
      transforms:
      - type: map
        map:
          small: Standard_D2_v2
          medium: Standard_B4ms
          large: Standard_D8s_v3
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: status.clusterName
    - type: ToCompositeFieldPath
      fromFieldPath: spec.forProvider.location
      toFieldPath: status.region
    - type: ToCompositeFieldPath
      fromFieldPath: status.conditions.status
      toFieldPath: status.controlPlaneStatus
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-akscluster"
  - name: attachedCluster
    base:
      apiVersion: containerattached.gcp.gke.cloud.google.com/v1beta1
      kind: Cluster
      metadata:
        name: attachedcluster
      spec:
        providerConfigRef:
          name: default-gcp
        forProvider:
          distribution: aks
          location: us-west1
          fleet:
          - project: "project/<project-number>"
    patches:
    - fromFieldPath: spec.parameters.k8sVersion
      toFieldPath: spec.forProvider.platformVersion
      transforms:
      - type: map
        map:
          1.24: 1.24.0-gke.1
          1.25: 1.25.0-gke.2
    - fromFieldPath: status.odicIssuerUrl
      toFieldPath: spec.forProvider.oidcConfig[0].issuerUrl
    - fromFieldPath: spec.parameters.fleetProject
      toFieldPath: spec.forProvider.fleet[0].project
      transforms:
      - type: string
        string:
          fmt: "projects/%s"
    - fromFieldPath: spec.parameters.adminUsers
      toFieldPath: spec.forProvider.authorization[0].adminUsers
    - fromFieldPath: status.clusterName
      toFieldPath: metadata.annotations[crossplane.io/external-name]
  - name: clusterbootstrap
    base:
      apiVersion: containerattached.gcp.gke.cloud.google.com/v1beta1
      kind: ClusterBootstrapJob
      metadata:
        name: installmanifest
        labels:
          name: attachedclusterbootstrap
      spec:
        clusterConfig:
          project: ""
          id: ""
          location: us-west1
          platformVersion: ""
        clusterCredentials:
          source: Secret
          secretRef:
            namespace: default
            key: kubeconfig
    patches:
    - fromFieldPath: spec.parameters.k8sVersion
      toFieldPath: spec.clusterConfig.platformVersion
      transforms:
      - type: map
        map:
          1.24: 1.24.0-gke.1
          1.25: 1.25.0-gke.2
    - fromFieldPath: status.clusterName
      toFieldPath: spec.clusterConfig.id
    - fromFieldPath: spec.parameters.fleetProject
      toFieldPath: spec.clusterConfig.project
    - fromFieldPath: metadata.uid
      toFieldPath: spec.clusterCredentials.secretRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-akscluster"
    readinessChecks:
    - type: NonEmpty
      fieldPath: status.succeeded