apiVersion: demo.anthos.com/v1
kind: CompositeCluster 
metadata:
  name: test-cluster2
spec:
  compositionRef:
    name: cluster-anthos-aws
  parameters:
    nodeSize: medium
    k8sVersion: "1.25"
    fleetProject: "261832825633"
    minNodeCount: 2
    adminUsers:
    - zicong@google.com
  writeConnectionSecretToRef:
    namespace: default
    name: b-team
