apiVersion: aws.gke.cloud.google.com/v1beta1
kind: ProviderConfig
metadata:
  name: default-aws
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-config
      name: aws-creds
      key: creds
  endpoint:
    signingRegion: us-east-1