apiVersion: demo.anthos.com/v1
kind: CompositeCluster 
metadata:
  name: test-cluster2
spec:
  compositionRef:
    # Possible values cluster-gcp-gke, cluster-aws-eks, cluster-azure-aks
    name: cluster-aws-eks
  parameters:
    # Possible values small, medium, large
    nodeSize: medium
    k8sVersion: "1.25"
    fleetProject: "261832825633"
    minNodeCount: 2
    adminUsers:
    - bkauf@google.com  
  writeConnectionSecretToRef:
    namespace: default
    name: b-team
